import { SaaSPlanner } from "../../planner/SaaSPlanner";
import type { ProjectRegistry } from "../../projects/ProjectRegistry";
import type {
  GeneratePlanOptions,
  PlannerModelPort,
} from "../ports/PlannerModelPort";
import type { Plan, PlanningContext, PlanPhase } from "../types";

function toPlanPhases(plan: Plan): PlanPhase[] {
  return plan.jobs.map((job) => ({
    phase: job.phase,
    summary: `${job.tasks.length} task(s) planned for phase ${job.phase}.`,
    taskCount: job.tasks.length,
  }));
}

export class HeuristicPlannerModel implements PlannerModelPort {
  private readonly planner: SaaSPlanner;

  constructor(registry: ProjectRegistry) {
    this.planner = new SaaSPlanner(registry);
  }

  async generatePlan(
    context: PlanningContext,
    options: GeneratePlanOptions = {}
  ): Promise<Plan> {
    const jobs = this.planner.plan(context.scan, context.risks, {
      preferences: {
        preferredStack: context.memory.preferences.preferredStack,
        defaultDomain: context.memory.preferences.defaultDomain,
        codingStyle: context.memory.preferences.codingStyle,
        autoApproveLowRisk: context.memory.preferences.autoApproveLowRisk,
      },
      recentProjects: context.memory.recentProjects,
      recentDecisions: context.memory.recentDecisions,
    });

    const plan: Plan = {
      objective: context.objective,
      project: {
        id: context.project.id,
        name: context.project.name,
        rootPath: context.project.rootPath,
        currentPhase: context.project.currentPhase,
      },
      goals: [context.objective.raw],
      steps: [],
      agentsRequired: [],
      dependencies: [],
      risks: context.risks.map((risk) => ({
        id: risk.id,
        level: risk.risk,
        title: risk.title,
        summary: risk.detail,
      })),
      confidence: 0.4,
      reasoningSummary:
        "Plan generated by the transitional planner adapter using the existing SaaSPlanner rules.",
      jobs,
      phases: [],
      summary: {
        totalJobs: jobs.length,
        totalTasks: jobs.reduce((acc, job) => acc + job.tasks.length, 0),
        highRiskCount: context.risks.filter((risk) => risk.risk === "HIGH").length,
      },
      metadata: {
        planner: "heuristic-saas-planner",
        memoryRecordCount: context.memory.records.length,
        candidateIndex: options.candidateIndex ?? 0,
        totalCandidates: options.totalCandidates ?? 1,
      },
    };

    plan.phases = toPlanPhases(plan);
    return plan;
  }
}
